// constants for basic info object
export const LOAD_BROWSER_NAME = 'LOAD_BROWSER_NAME';
export const LOAD_BROWSER_VERSION = 'LOAD_BROWSER_VERSION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const SHOW_USER_DETAILS = 'SHOW_USER_DETAILS'
export const SHOW_UNIVERSITIES = 'SHOW_UNIVERSITIES'
